# Generated by Django 2.2.1 on 2019-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190520_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_solv',
            field=models.TextField(blank=True, default='Task_text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(blank=True, default='Task_text'),
            preserve_default=False,
        ),
    ]
